name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  Publish-NPM:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@thundernetworkrad'
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          REGISTRY1: 'registry.npmjs.org'
          REGISTRY2: 'registry=https://registry.npmjs.org/'

  Publish-GitHub-NPM:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@thundernetworkrad'
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GP_TOKEN }}
          REGISTRY1: 'npm.pkg.github.com'
          REGISTRY2: '@thundernetworkrad:registry=https://npm.pkg.github.com'
